import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { unsupported } from "../errors";
import { asRecord, numberValue, parseJsonLines } from "../jsonl";
import { probeExecutable, runInvocation } from "../process";
import type {
  AgentUsage,
  Invocation,
  ListModelsOptions,
  ParsedOutput,
  PrepareOptions,
  ProviderAdapter,
  ProviderCapabilities,
  RunRequest,
} from "../types";
import {
  assertAccess,
  assertSession,
  envExecutable,
  findTerminalMarker,
  providerFailureMessage,
  textOutput,
} from "./shared";

function cursorModel(model: string, effort: RunRequest["effort"]): string {
  if (!effort) return model;
  const suffix = model.match(/-(none|low|medium|high|xhigh|max|extra-high)(?:-fast)?$/u)?.[1];
  if (suffix === effort || (effort === "xhigh" && suffix === "extra-high")) return model;
  const match = model.match(/^(.*)\[([^\]]*)\]$/u);
  if (!match) return `${model}[effort=${effort}]`;
  const parameters = match[2]!;
  const existing = parameters.match(/(?:^|,)effort=([^,]+)/u)?.[1];
  if (existing === effort) return model;
  if (existing) return `${match[1]}[${parameters.replace(/(^|,)effort=[^,]+/u, `$1effort=${effort}`)}]`;
  return `${match[1]}[${parameters}${parameters ? "," : ""}effort=${effort}]`;
}

/**
 * Model used when a Cursor request names none. Cursor has no usable server-side
 * default here (`auto` is deliberately refused), so the runner has to pick one.
 * Verified present in the live `models` list of `cursor-agent 2026.08.04-aaa8809`.
 *
 * A run that falls back to this reports `modelDefaulted: true`. Callers whose
 * correctness depends on *who* chose the model - cold review, for instance,
 * requires an operator-chosen reviewer from a different family than the
 * implementer - must check that flag rather than compare against this string.
 */
export const CURSOR_DEFAULT_MODEL = "cursor-grok-4.5-medium";

/** Marks a worktree name as generated by this runner rather than by a caller. */
export const WORKTREE_NAME_PREFIX = "agent-headless";

/**
 * Names an isolated worktree when the caller did not. Cursor accepts a bare
 * `--worktree` and then picks its own name, which it never reports back - so a
 * run whose stream is unreadable leaves work at an unrecoverable path. Passing a
 * name we chose keeps the worktree locatable from the result alone.
 *
 * Shape: `agent-headless-<ms-timestamp-base36>-<48 random bits, hex>`, lowercase
 * alphanumeric and dashes only, ~33 characters. The random half comes from
 * `randomUUID` (CSPRNG), so two concurrent runs collide only if they draw the
 * same 48-bit value *and* start in the same millisecond - about 3.6e-15 per pair.
 */
export function generateWorktreeName(): string {
  return `${WORKTREE_NAME_PREFIX}-${Date.now().toString(36)}-${randomUUID().replace(/-/gu, "").slice(0, 12)}`;
}

/**
 * Returns a request whose isolated runs always carry an explicit worktree name.
 * A caller-supplied name is left untouched; the guarantee must not depend on
 * every caller remembering to pass one.
 */
export function withDefaultWorktreeName(request: RunRequest, generate: () => string): RunRequest {
  if (request.access !== "edit-isolated") return request;
  const cursor = request.providerOptions?.cursor;
  if (cursor?.worktreeName) return request;
  return {
    ...request,
    providerOptions: {
      ...request.providerOptions,
      cursor: { ...cursor, worktreeName: generate() },
    },
  };
}

/**
 * Environment variable Cursor reads to relocate the directory that holds every
 * named worktree. Unset, Cursor uses `~/.cursor/worktrees`.
 */
export const CURSOR_WORKTREES_ROOT_ENV = "CURSOR_WORKTREES_ROOT";

/**
 * Names Cursor accepts for `--worktree`. Cursor validates rather than sanitizes:
 * anything outside this set aborts the run, so a name that fails it never
 * produces a worktree and must never produce a derived path either.
 */
export const CURSOR_WORKTREE_NAME_PATTERN = /^[A-Za-z0-9._-]+$/u;

/**
 * Reads a variable as the launched child will see it. `runInvocation` overlays
 * `request.env` onto the inherited environment, where an explicit `undefined`
 * *removes* the variable - so an overlay entry always wins, even when its value
 * is `undefined`, and only the absence of an entry falls through to
 * `process.env`. Key matching is case-insensitive on Windows for the same
 * reason it is there: Windows environment variables are.
 */
function childEnvValue(name: string, env?: Record<string, string | undefined>): string | undefined {
  for (const key of Object.keys(env ?? {})) {
    const matches = process.platform === "win32" ? key.toLowerCase() === name.toLowerCase() : key === name;
    if (matches) return env![key];
  }
  return process.env[name];
}

/**
 * Directory Cursor will place named worktrees under, or `undefined` when it
 * cannot be determined (no resolvable home directory and no explicit override).
 * An empty override is passed through rather than replaced, because Cursor
 * itself only substitutes the default when the variable is entirely absent.
 */
export function cursorWorktreesRoot(env?: Record<string, string | undefined>): string | undefined {
  const configured = childEnvValue(CURSOR_WORKTREES_ROOT_ENV, env);
  if (configured !== undefined) return configured;
  try {
    const home = homedir();
    return home ? path.join(home, ".cursor", "worktrees") : undefined;
  } catch {
    return undefined;
  }
}

/** Mirrors Cursor's slugging of the repository directory name. */
function slugifyRepoName(name: string): string {
  const slug = name.toLowerCase()
    .replace(/[^a-z0-9._-]+/gu, "-")
    .replace(/-+/gu, "-")
    .replace(/^-+|-+$/gu, "");
  return slug || "worktree";
}

/**
 * The per-repository directory Cursor nests worktrees in: the slugified base
 * name of the repository root. Cursor finds that root with
 * `git rev-parse --show-toplevel`; walking up for a `.git` entry finds the same
 * directory (a linked worktree or submodule has a `.git` *file* at its root)
 * without spending a subprocess on every run. Returns `undefined` outside a Git
 * repository, where an isolated Cursor run cannot start at all.
 */
export function cursorRepoSlug(cwd: string): string | undefined {
  let current = path.resolve(cwd);
  for (;;) {
    if (existsSync(path.join(current, ".git"))) return slugifyRepoName(path.basename(current));
    const parent = path.dirname(current);
    if (parent === current) return undefined;
    current = parent;
  }
}

/**
 * Where an isolated Cursor run's worktree is, computed *before* the provider
 * emits anything. Cursor places a named worktree at
 * `<worktrees-root>/<repo-slug>/<name>`, and the runner always pins the name -
 * so the location is a function of the request, not of the provider's output.
 * That is what keeps a run locatable when its stream is unreadable, the very
 * case a parsed path cannot cover.
 *
 * `undefined` (never a guess) when any input is missing: a non-isolated or
 * non-Cursor request, a name Cursor would reject, no determinable root, or a
 * cwd outside a Git repository.
 */
export function cursorWorktreePath(request: RunRequest, cwd: string = request.cwd): string | undefined {
  if (request.provider !== "cursor" || request.access !== "edit-isolated") return undefined;
  const name = request.providerOptions?.cursor?.worktreeName;
  if (!name || !CURSOR_WORKTREE_NAME_PATTERN.test(name)) return undefined;
  const root = cursorWorktreesRoot(request.env);
  const slug = cursorRepoSlug(cwd);
  if (root === undefined || slug === undefined) return undefined;
  // Resolved against cwd because Cursor resolves a relative root against its own
  // working directory, which is this cwd; an absolute root is unaffected.
  return path.resolve(cwd, root, slug, name);
}

const modelPromises = new Map<string, Promise<string[]>>();

/**
 * Cache key for a model listing, covering the whole environment it was made
 * under - two installations, or two accounts, can offer different models.
 *
 * `JSON.stringify` on the env object cannot be used: it drops properties whose
 * value is `undefined`, so `{ CURSOR_API_KEY: undefined }` and `{}` would
 * collapse to one key even though `runInvocation` treats them oppositely (the
 * first deletes an inherited credential, the second keeps it). Encoding each
 * property as a tuple - `[name]` when present-but-undefined, `[name, value]`
 * otherwise - keeps those two apart, and sorting by name makes the key
 * independent of property insertion order.
 *
 * Scope note: this deliberately keys only the *overrides*. A run whose
 * credentials come from inherited `process.env` shares a key with any other
 * such run, and a mid-process mutation of `process.env` will not invalidate the
 * cache. That is the pre-existing contract (the memo lives for the process
 * lifetime), and inherited-env mutation is not something a caller does between
 * two listings in practice.
 */
export function modelListingKey(executable: string, env?: Record<string, string | undefined>): string {
  const entries = env
    ? Object.keys(env).sort().map((name) => (env[name] === undefined ? [name] : [name, env[name]]))
    : null;
  return JSON.stringify([executable, entries]);
}

function parseModels(stdout: string): string[] {
  return stdout.split(/\r?\n/u)
    .map((line) => line.match(/^([^\s]+)\s+-\s+/u)?.[1])
    .filter((model): model is string => Boolean(model));
}

function modelWithEffort(model: string, effort: Exclude<RunRequest["effort"], undefined>): string {
  const fast = model.endsWith("-fast") ? "-fast" : "";
  const withoutFast = fast ? model.slice(0, -fast.length) : model;
  const match = withoutFast.match(/^(.*)-(none|low|medium|high|xhigh|max|extra-high)$/u);
  const base = match?.[1] ?? withoutFast;
  return `${base}-${effort}${fast}`;
}

export class CursorAdapter implements ProviderAdapter {
  readonly provider = "cursor" as const;

  async capabilities(executable = envExecutable(this.provider)): Promise<ProviderCapabilities> {
    const probe = await probeExecutable(this.provider, executable, process.cwd());
    return {
      provider: this.provider,
      executable: probe.executable,
      availability: probe.availability,
      ...(probe.version ? { version: probe.version } : {}),
      ...(probe.reason ? { availabilityReason: probe.reason } : {}),
      access: ["answer-only", "inspect", "edit-isolated"],
      sessions: ["persistent", "resume"],
      supportsModel: true,
      supportsEffort: true,
      supportsSchema: false,
      supportsModelListing: true,
    };
  }

  async listModels(options: ListModelsOptions = {}): Promise<string[]> {
    const executable = options.executable ?? envExecutable(this.provider, options.env);
    const key = modelListingKey(executable, options.env);
    let modelsPromise = modelPromises.get(key);
    if (!modelsPromise) {
      modelsPromise = (async () => {
        const result = await runInvocation(
          { provider: this.provider, command: executable, args: ["models"], cwd: process.cwd(), stdin: "", structured: false },
          { timeoutMs: 30_000, ...(options.env ? { env: options.env } : {}) },
        );
        if (result.exitCode !== 0) unsupported(`Cursor model listing failed: ${result.stderr.trim()}`);
        return parseModels(result.stdout);
      })();
      modelPromises.set(key, modelsPromise);
    }
    return await modelsPromise;
  }

  async prepare(request: RunRequest, options: PrepareOptions = {}): Promise<RunRequest> {
    // An operator-supplied model always wins; the default only fills a gap.
    const model = request.model ?? CURSOR_DEFAULT_MODEL;
    const withModel: RunRequest = request.model === undefined ? { ...request, model } : request;
    // Fix the worktree name here, so build and the workspace descriptor agree on it.
    const defaulted = withDefaultWorktreeName(withModel, options.generateWorktreeName ?? generateWorktreeName);
    if (!request.effort || model.includes("[")) return defaulted;
    const models = await this.listModels({
      executable: envExecutable(this.provider, request.env),
      ...(request.env ? { env: request.env } : {}),
    });
    const candidate = modelWithEffort(model, request.effort);
    const xhighCandidate = request.effort === "xhigh"
      ? modelWithEffort(model, "high").replace(/-high(-fast)?$/u, "-extra-high$1")
      : undefined;
    const resolved = [candidate, xhighCandidate].find((value) => value && models.includes(value));
    if (resolved) return { ...defaulted, model: resolved };
    if (models.includes(model)) {
      unsupported(`Cursor model ${model} has no available ${request.effort} effort variant; choose an exact model ID`);
    }
    return defaulted;
  }

  build(request: RunRequest): Invocation {
    assertAccess(request, ["answer-only", "inspect", "edit-isolated"]);
    assertSession(request, ["persistent", "resume"]);
    // `prepare` normally fills this in; repeated here so a direct `build` matches.
    const model = request.model ?? CURSOR_DEFAULT_MODEL;
    if (model.toLowerCase() === "auto") unsupported("Cursor model=auto is not allowed; name an exact model");
    if (request.schema) unsupported("Cursor does not support JSON Schema-constrained output");
    if (request.maxBudgetUsd !== undefined) unsupported("Cursor does not expose a per-run budget flag");

    const args = ["--print", "--workspace", request.cwd, "--model", cursorModel(model, request.effort)];
    // `prepare` normally fixed the name already; a direct build must not emit a
    // bare `--worktree`, whose Cursor-chosen path is never reported back to us.
    const options = withDefaultWorktreeName(request, generateWorktreeName).providerOptions?.cursor;
    if (options?.trustWorkspace) args.push("--trust");
    if (request.output === "events") {
      args.push("--output-format", "stream-json");
      if (options?.streamPartialOutput) args.push("--stream-partial-output");
    }
    if (request.access === "answer-only") args.push("--mode", "ask");
    if (request.access === "inspect") args.push("--mode", "plan");
    if (request.access === "edit-isolated") {
      args.push("--worktree", options!.worktreeName!);
      // `--worktree-base` is the Git ref the new worktree branches from, not a
      // directory. The worktree's *location* has no flag: Cursor always uses
      // `<CURSOR_WORKTREES_ROOT|~/.cursor/worktrees>/<repo-slug>/<name>`, which
      // `cursorWorktreePath` reconstructs.
      if (options?.worktreeBase) args.push("--worktree-base", options.worktreeBase);
      if (process.platform !== "win32") args.push("--sandbox", "enabled");
    }
    if (request.session!.mode === "persistent" && request.session!.id) {
      unsupported("Cursor cannot select a session ID when starting a persistent session");
    }
    if (request.session!.mode === "resume") args.push("--resume", request.session!.id);
    for (const directory of request.additionalDirs ?? []) args.push("--add-dir", directory);

    return {
      provider: this.provider,
      command: envExecutable(this.provider, request.env),
      args,
      cwd: request.cwd,
      stdin: request.prompt,
      structured: request.output === "events",
    };
  }

  parse(stdout: string, structured: boolean): ParsedOutput {
    if (!structured) return textOutput(this.provider, stdout);
    const parsed = parseJsonLines(this.provider, stdout);
    const warnings = parsed.warnings.length ? { warnings: parsed.warnings } : {};
    if (parsed.error) return { events: parsed.events, protocolError: parsed.error, unreadable: true, ...warnings };
    // Last terminal marker wins, as for the other providers: a result followed
    // by an `error` is a failure, an `error` followed by a later result is not.
    const terminal = findTerminalMarker(parsed.events, (event) => event.type.startsWith("result"));
    if (terminal?.outcome === "failure") {
      return { events: parsed.events, protocolError: providerFailureMessage("Cursor", terminal.event), ...warnings };
    }
    const result = asRecord(terminal?.event.raw);
    if (!result) {
      // Readable, but with no terminal marker at all: genuinely ambiguous.
      return { events: parsed.events, protocolError: "Cursor stream did not contain a terminal result", unreadable: true, ...warnings };
    }
    if (result.is_error === true || result.subtype !== "success") {
      return { events: parsed.events, protocolError: String(result.result ?? "Cursor reported an error"), ...warnings };
    }
    const init = asRecord(parsed.events.find((event) => event.type.startsWith("system"))?.raw);
    const rawUsage = asRecord(result.usage);
    const usage: AgentUsage = {};
    const inputTokens = numberValue(rawUsage?.inputTokens);
    const cachedInputTokens = numberValue(rawUsage?.cacheReadTokens);
    const outputTokens = numberValue(rawUsage?.outputTokens);
    if (inputTokens !== undefined) usage.inputTokens = inputTokens;
    if (cachedInputTokens !== undefined) usage.cachedInputTokens = cachedInputTokens;
    if (outputTokens !== undefined) usage.outputTokens = outputTokens;
    return {
      events: parsed.events,
      ...(typeof result.result === "string" ? { finalText: result.result } : {}),
      ...(typeof result.session_id === "string" ? { sessionId: result.session_id } : typeof init?.session_id === "string" ? { sessionId: init.session_id } : {}),
      ...(typeof init?.model === "string" ? { modelObserved: init.model } : {}),
      ...(Object.keys(usage).length ? { usage } : {}),
      ...warnings,
    };
  }
}
