import { spawnSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { unsupported } from "../errors";
import { assertSupportedModel, supportedModels } from "../models";
import { asRecord, numberValue, parseJsonLines } from "../jsonl";
import { effectiveEnv, foldEnvName, lastEnvMatch, probeExecutable, resolveCommand } from "../process";
import type {
  AgentUsage,
  Invocation,
  ParsedOutput,
  PrepareOptions,
  ProviderAdapter,
  ProviderCapabilities,
  RunRequest,
} from "../types";
import {
  assertAccess,
  assertSession,
  envExecutable,
  findTerminalMarker,
  providerFailureMessage,
  textOutput,
} from "./shared";

function cursorModel(model: string, effort: RunRequest["effort"]): string {
  if (!effort) return model;
  const suffix = model.match(/-(none|low|medium|high|xhigh|max|extra-high)(?:-fast)?$/u)?.[1];
  if (suffix === effort || (effort === "xhigh" && suffix === "extra-high")) return model;
  const match = model.match(/^(.*)\[([^\]]*)\]$/u);
  if (!match) return `${model}[effort=${effort}]`;
  const parameters = match[2]!;
  const existing = parameters.match(/(?:^|,)effort=([^,]+)/u)?.[1];
  if (existing === effort) return model;
  if (existing) return `${match[1]}[${parameters.replace(/(^|,)effort=[^,]+/u, `$1effort=${effort}`)}]`;
  return `${match[1]}[${parameters}${parameters ? "," : ""}effort=${effort}]`;
}

/**
 * Model used when a Cursor request names none. Cursor has no usable server-side
 * default here (`auto` is deliberately refused), so the runner has to pick one.
 * Must stay on the supported Cursor list (`SUPPORTED_MODELS.cursor`).
 *
 * A run that falls back to this reports `modelDefaulted: true`. Callers whose
 * correctness depends on *who* chose the model - cold review, for instance,
 * requires an operator-chosen reviewer from a different family than the
 * implementer - must check that flag rather than compare against this string.
 */
export const CURSOR_DEFAULT_MODEL = "cursor-grok-4.5-medium";

/** Marks a worktree name as generated by this runner rather than by a caller. */
export const WORKTREE_NAME_PREFIX = "agent-headless";

/**
 * Names an isolated worktree when the caller did not. Cursor accepts a bare
 * `--worktree` and then picks its own name, which it never reports back - so a
 * run whose stream is unreadable leaves work at an unrecoverable path. Passing a
 * name we chose keeps the worktree locatable from the result alone.
 *
 * Shape: `agent-headless-<ms-timestamp-base36>-<48 random bits, hex>`, lowercase
 * alphanumeric and dashes only, ~33 characters. The random half comes from
 * `randomUUID` (CSPRNG), so two concurrent runs collide only if they draw the
 * same 48-bit value *and* start in the same millisecond - about 3.6e-15 per pair.
 */
export function generateWorktreeName(): string {
  return `${WORKTREE_NAME_PREFIX}-${Date.now().toString(36)}-${randomUUID().replace(/-/gu, "").slice(0, 12)}`;
}

/**
 * Returns a request whose isolated runs always carry an explicit worktree name.
 * A caller-supplied name is left untouched; the guarantee must not depend on
 * every caller remembering to pass one.
 */
export function withDefaultWorktreeName(request: RunRequest, generate: () => string): RunRequest {
  if (request.access !== "edit-isolated") return request;
  const cursor = request.providerOptions?.cursor;
  if (cursor?.worktreeName) return request;
  return {
    ...request,
    providerOptions: {
      ...request.providerOptions,
      cursor: { ...cursor, worktreeName: generate() },
    },
  };
}

/**
 * Environment variable Cursor reads to relocate the directory that holds every
 * named worktree. Unset, Cursor uses `~/.cursor/worktrees`.
 */
export const CURSOR_WORKTREES_ROOT_ENV = "CURSOR_WORKTREES_ROOT";

/**
 * Names Cursor accepts for `--worktree`. Cursor validates rather than sanitizes:
 * anything outside this set aborts the run, so a name that fails it never
 * produces a worktree and must never produce a derived path either.
 */
export const CURSOR_WORKTREE_NAME_PATTERN = /^[A-Za-z0-9._-]+$/u;

/**
 * Reads a variable as the launched child will see it. `runInvocation` overlays
 * `request.env` onto the inherited environment, where an explicit `undefined`
 * *removes* the variable - so an overlay entry always wins, even when its value
 * is `undefined`, and only the absence of an entry falls through to
 * `process.env`. Key matching is case-insensitive on Windows for the same
 * reason it is there: Windows environment variables are.
 */
function childEnvValue(name: string, env?: Record<string, string | undefined>): string | undefined {
  // One matcher, shared with envValue: lastEnvMatch. What stays distinct here
  // is only the fallthrough - a present-but-undefined entry means the child
  // sees the variable DELETED, so it must not fall through to process.env.
  const { matched, value } = lastEnvMatch(env ?? {}, name);
  return matched ? value : process.env[name];
}

/**
 * Directory Cursor will place named worktrees under, or `undefined` when it
 * cannot be determined (no resolvable home directory and no explicit override).
 * An empty override is passed through rather than replaced, because Cursor
 * itself only substitutes the default when the variable is entirely absent.
 */
export function cursorWorktreesRoot(env?: Record<string, string | undefined>): string | undefined {
  const configured = childEnvValue(CURSOR_WORKTREES_ROOT_ENV, env);
  if (configured !== undefined) return configured;
  try {
    const home = homedir();
    return home ? path.join(home, ".cursor", "worktrees") : undefined;
  } catch {
    return undefined;
  }
}

/** Mirrors Cursor's slugging of the repository directory name. */
function slugifyRepoName(name: string): string {
  const slug = name.toLowerCase()
    .replace(/[^a-z0-9._-]+/gu, "-")
    .replace(/-+/gu, "-")
    .replace(/^-+|-+$/gu, "");
  return slug || "worktree";
}

/**
 * Cheap negative pre-check: is there any `.git` entry at or above `cwd`? A real
 * repository always has one (a linked worktree or submodule has a `.git` *file*),
 * so a `false` here rules out a repository without spending a subprocess. It is
 * deliberately *not* sufficient on its own - an empty or malformed `.git` passes
 * this and is still not a repository, which is what `git` below decides.
 */
function hasGitAncestor(start: string): boolean {
  let current = start;
  for (;;) {
    if (existsSync(path.join(current, ".git"))) return true;
    const parent = path.dirname(current);
    if (parent === current) return false;
    current = parent;
  }
}

/**
 * The repository root, resolved exactly as Cursor resolves it:
 * `git rev-parse --show-toplevel`, run in the same directory the provider will
 * be launched in. `undefined` on every failure - git missing, not a repository,
 * an empty or malformed `.git`, a cwd that does not exist - because each of
 * those is a case where Cursor itself refuses to create a worktree, and a path
 * derived from them could never exist.
 *
 * Run under the *request's* environment, not the parent's. The whole worth of an
 * absent `workspace.worktree` is that it proves no worktree exists; that holds
 * only if the probe and the provider see git identically. A caller who hands
 * Cursor a `PATH` on which git is reachable, while the parent's is not, would
 * otherwise get a real worktree plus a result claiming there is none. Both the
 * environment and the command resolution come from the same helpers
 * `runInvocation` uses, so the two cannot drift.
 */
function gitToplevel(cwd: string, env?: Record<string, string | undefined>): string | undefined {
  try {
    const childEnv = effectiveEnv(env);
    const resolved = resolveCommand("git", ["rev-parse", "--show-toplevel"], childEnv);
    const result = spawnSync(resolved.command, resolved.args, {
      cwd,
      env: childEnv,
      encoding: "utf8",
      windowsHide: true,
      windowsVerbatimArguments: resolved.windowsVerbatimArguments,
      timeout: 10_000,
    });
    if (result.error || result.status !== 0) return undefined;
    // git prints forward slashes even on Windows; resolve normalizes them.
    const toplevel = result.stdout.trim();
    return toplevel ? path.resolve(toplevel) : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Encodes an environment overlay as a cache-key fragment.
 *
 * `JSON.stringify` on the env object cannot be used: it drops properties whose
 * value is `undefined`, so `{ CURSOR_API_KEY: undefined }` and `{}` would
 * collapse to one key even though `runInvocation` treats them oppositely (the
 * first deletes an inherited credential, the second keeps it). Encoding each
 * property as a tuple - `[name]` when present-but-undefined, `[name, value]`
 * otherwise - keeps those two apart, and sorting by name makes the key
 * independent of property insertion order. `null` marks "no overlay at all",
 * which is again distinct from an empty one.
 */
function envKeyPart(env?: Record<string, string | undefined>): (string[])[] | null {
  if (!env) return null;
  // Folding and winner selection are not reimplemented here: foldEnvName
  // decides which names are the same variable and lastEnvMatch decides which
  // entry wins, so this key cannot drift from how the overlay resolves.
  const names = [...new Set(Object.keys(env).map(foldEnvName))].sort();
  return names.map((name) => {
    const { value } = lastEnvMatch(env, name);
    return value === undefined ? [name] : [name, value];
  });
}

/**
 * Memo of resolved-cwd plus probe environment to slug. `describeWorkspace` runs
 * once for the partial result and again for the final one, so an un-memoized
 * lookup would spend two subprocesses per run for one unchanging answer.
 *
 * The environment is part of the key because it is part of the question: the
 * probe runs `git` as the request's environment defines it, so two requests that
 * differ only in `PATH` can legitimately resolve one cwd to different roots (or
 * to a root and to nothing). Keying on cwd alone would let the first answer
 * stand in for the second and reintroduce exactly the parity break the env
 * threading fixes.
 */
const repoSlugCache = new Map<string, string | undefined>();

function repoSlugKey(cwd: string, env?: Record<string, string | undefined>): string {
  return JSON.stringify([cwd, envKeyPart(env)]);
}

/**
 * The per-repository directory Cursor nests worktrees in: the slugified base
 * name of the repository root. Returns `undefined` wherever Cursor could not
 * start an isolated run - outside a Git repository, or where a `.git` entry
 * exists but is not a usable one. Accepting a bare `.git` entry as proof of a
 * repository would derive a path no worktree can ever occupy, which is exactly
 * the fabrication this runner promises never to commit.
 *
 * `env` is the run's environment overlay (`request.env`), applied to the probe
 * exactly as it will be applied to Cursor itself; omitting it probes under the
 * inherited environment.
 *
 * Memoized per resolved `cwd` *and* probe environment for the process lifetime,
 * so a directory that becomes (or stops being) a repository mid-process keeps
 * its first answer - the same lifetime contract the model listing memo carries.
 */
export function cursorRepoSlug(cwd: string, env?: Record<string, string | undefined>): string | undefined {
  const start = path.resolve(cwd);
  const key = repoSlugKey(start, env);
  const cached = repoSlugCache.get(key);
  if (cached !== undefined || repoSlugCache.has(key)) return cached;
  const toplevel = hasGitAncestor(start) ? gitToplevel(start, env) : undefined;
  const slug = toplevel === undefined ? undefined : slugifyRepoName(path.basename(toplevel));
  repoSlugCache.set(key, slug);
  return slug;
}

/**
 * Where an isolated Cursor run's worktree is, computed *before* the provider
 * emits anything. Cursor places a named worktree at
 * `<worktrees-root>/<repo-slug>/<name>`, and the runner always pins the name -
 * so the location is a function of the request, not of the provider's output.
 * That is what keeps a run locatable when its stream is unreadable, the very
 * case a parsed path cannot cover.
 *
 * `undefined` (never a guess) when any input is missing: a non-isolated or
 * non-Cursor request, a name Cursor would reject, no determinable root, or a
 * cwd `git rev-parse --show-toplevel` - run under `env`, the same environment
 * overlay the Cursor invocation gets - does not resolve to a repository root.
 */
export function cursorWorktreePath(
  request: RunRequest,
  cwd: string = request.cwd,
  env: Record<string, string | undefined> | undefined = request.env,
): string | undefined {
  if (request.provider !== "cursor" || request.access !== "edit-isolated") return undefined;
  const name = request.providerOptions?.cursor?.worktreeName;
  if (!name || !CURSOR_WORKTREE_NAME_PATTERN.test(name)) return undefined;
  const root = cursorWorktreesRoot(env);
  const slug = cursorRepoSlug(cwd, env);
  if (root === undefined || slug === undefined) return undefined;
  // Resolved against cwd because Cursor resolves a relative root against its own
  // working directory, which is this cwd; an absolute root is unaffected.
  return path.resolve(cwd, root, slug, name);
}

/**
 * Cache-key helper retained for callers and tests that need the same environment
 * encoding `cursorRepoSlug` uses. Model listing itself is a static supported
 * list and no longer probes the Cursor CLI.
 */
export function modelListingKey(executable: string, env?: Record<string, string | undefined>): string {
  return JSON.stringify([executable, envKeyPart(env)]);
}

function modelWithEffort(model: string, effort: Exclude<RunRequest["effort"], undefined>): string {
  const fast = model.endsWith("-fast") ? "-fast" : "";
  const withoutFast = fast ? model.slice(0, -fast.length) : model;
  const match = withoutFast.match(/^(.*)-(none|low|medium|high|xhigh|max|extra-high)$/u);
  const base = match?.[1] ?? withoutFast;
  return `${base}-${effort}${fast}`;
}

export class CursorAdapter implements ProviderAdapter {
  readonly provider = "cursor" as const;

  async capabilities(executable = envExecutable(this.provider)): Promise<ProviderCapabilities> {
    const probe = await probeExecutable(this.provider, executable, process.cwd());
    return {
      provider: this.provider,
      executable: probe.executable,
      availability: probe.availability,
      ...(probe.version ? { version: probe.version } : {}),
      ...(probe.reason ? { availabilityReason: probe.reason } : {}),
      access: ["answer-only", "inspect", "edit-isolated"],
      sessions: ["persistent", "resume"],
      supportsModel: true,
      supportsEffort: true,
      supportsSchema: false,
      supportsModelListing: true,
    };
  }

  async listModels(): Promise<string[]> {
    return supportedModels("cursor");
  }

  async prepare(request: RunRequest, options: PrepareOptions = {}): Promise<RunRequest> {
    const model = request.model ?? CURSOR_DEFAULT_MODEL;
    if (model.toLowerCase() === "auto") unsupported("Cursor model=auto is not allowed; name an exact model");
    let next: RunRequest = request.model === undefined ? { ...request, model } : { ...request };
    const models = supportedModels("cursor");
    if (request.effort && !model.includes("[")) {
      const candidate = modelWithEffort(model, request.effort);
      if (models.includes(candidate)) next = { ...next, model: candidate };
      else if (models.includes(model)) {
        unsupported(
          `Cursor model ${model} has no supported ${request.effort} effort variant; choose an exact model ID`,
        );
      }
    }
    assertSupportedModel("cursor", next.model!);
    return withDefaultWorktreeName(next, options.generateWorktreeName ?? generateWorktreeName);
  }

  build(request: RunRequest): Invocation {
    assertAccess(request, ["answer-only", "inspect", "edit-isolated"]);
    assertSession(request, ["persistent", "resume"]);
    // `prepare` normally fills this in; repeated here so a direct `build` matches.
    const model = request.model ?? CURSOR_DEFAULT_MODEL;
    if (model.toLowerCase() === "auto") unsupported("Cursor model=auto is not allowed; name an exact model");
    if (request.schema) unsupported("Cursor does not support JSON Schema-constrained output");
    if (request.maxBudgetUsd !== undefined) unsupported("Cursor does not expose a per-run budget flag");

    const args = ["--print", "--workspace", request.cwd, "--model", cursorModel(model, request.effort)];
    // `prepare` normally fixed the name already; a direct build must not emit a
    // bare `--worktree`, whose Cursor-chosen path is never reported back to us.
    const options = withDefaultWorktreeName(request, generateWorktreeName).providerOptions?.cursor;
    if (options?.trustWorkspace) args.push("--trust");
    if (request.output === "events") {
      args.push("--output-format", "stream-json");
      if (options?.streamPartialOutput) args.push("--stream-partial-output");
    }
    if (request.access === "answer-only") args.push("--mode", "ask");
    if (request.access === "inspect") args.push("--mode", "plan");
    if (request.access === "edit-isolated") {
      args.push("--worktree", options!.worktreeName!);
      // `--worktree-base` is the Git ref the new worktree branches from, not a
      // directory. The worktree's *location* has no flag: Cursor always uses
      // `<CURSOR_WORKTREES_ROOT|~/.cursor/worktrees>/<repo-slug>/<name>`, which
      // `cursorWorktreePath` reconstructs.
      if (options?.worktreeBase) args.push("--worktree-base", options.worktreeBase);
      if (process.platform !== "win32") args.push("--sandbox", "enabled");
    }
    if (request.session!.mode === "persistent" && request.session!.id) {
      unsupported("Cursor cannot select a session ID when starting a persistent session");
    }
    if (request.session!.mode === "resume") args.push("--resume", request.session!.id);
    for (const directory of request.additionalDirs ?? []) args.push("--add-dir", directory);

    return {
      provider: this.provider,
      command: envExecutable(this.provider, request.env),
      args,
      cwd: request.cwd,
      stdin: request.prompt,
      structured: request.output === "events",
    };
  }

  parse(stdout: string, structured: boolean): ParsedOutput {
    if (!structured) return textOutput(this.provider, stdout);
    const parsed = parseJsonLines(this.provider, stdout);
    const warnings = parsed.warnings.length ? { warnings: parsed.warnings } : {};
    if (parsed.error) return { events: parsed.events, protocolError: parsed.error, unreadable: true, ...warnings };
    // Last terminal marker wins, as for the other providers: a result followed
    // by an `error` is a failure, an `error` followed by a later result is not.
    const terminal = findTerminalMarker(parsed.events, (event) => event.type.startsWith("result"));
    if (terminal?.outcome === "failure") {
      return { events: parsed.events, protocolError: providerFailureMessage("Cursor", terminal.event), ...warnings };
    }
    const result = asRecord(terminal?.event.raw);
    if (!result) {
      // Readable, but with no terminal marker at all: genuinely ambiguous.
      return { events: parsed.events, protocolError: "Cursor stream did not contain a terminal result", unreadable: true, ...warnings };
    }
    if (result.is_error === true || result.subtype !== "success") {
      return { events: parsed.events, protocolError: String(result.result ?? "Cursor reported an error"), ...warnings };
    }
    const init = asRecord(parsed.events.find((event) => event.type.startsWith("system"))?.raw);
    const rawUsage = asRecord(result.usage);
    const usage: AgentUsage = {};
    const inputTokens = numberValue(rawUsage?.inputTokens);
    const cachedInputTokens = numberValue(rawUsage?.cacheReadTokens);
    const outputTokens = numberValue(rawUsage?.outputTokens);
    if (inputTokens !== undefined) usage.inputTokens = inputTokens;
    if (cachedInputTokens !== undefined) usage.cachedInputTokens = cachedInputTokens;
    if (outputTokens !== undefined) usage.outputTokens = outputTokens;
    return {
      events: parsed.events,
      ...(typeof result.result === "string" ? { finalText: result.result } : {}),
      ...(typeof result.session_id === "string" ? { sessionId: result.session_id } : typeof init?.session_id === "string" ? { sessionId: init.session_id } : {}),
      ...(typeof init?.model === "string" ? { modelObserved: init.model } : {}),
      ...(Object.keys(usage).length ? { usage } : {}),
      ...warnings,
    };
  }
}
